# Generated by Django 5.0.2 on 2024-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='messages',
            field=models.TextField(default='Django Developer'),
        ),
    ]
