# Generated by Django 5.0.2 on 2024-02-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_contact_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='messages',
            field=models.TextField(),
        ),
    ]
